 
 
# ---------------------------------------------------------------------------
# MUAP template generation - morphology-driven per muscle
#
# MUAP = Motor Unit Action Potential, using MUAP waveforms inside each
# burst generated via gaussian envelopes.
# Literature-based realistic MUAPs have biphasic/triphasic morphology.
#
# NOVEL CONTRIBUTION: rather than one fixed template that is scaled, the
# triphasic shape (phase timing, widths, amplitude ratios) is parameterized
# by muscle profile. The MUAP waveform itself changes between muscles.
# The Gaussian envelope triphasic model is the standard approach for MUAP
# simulation (Stashuk 2001, Nandedkar et al. 1988), but parameterizing
# it per-muscle with literature-derived durations and proportional phase
# scaling is our contribution. The phase_centers, phase_widths, and
# phase_amplitudes values are scaled proportionally to the Buchthal
# duration; they are NOT directly from a single paper.
# ---------------------------------------------------------------------------
 
def _muap_template(fs, profile: MuscleProfile):
    """
    Generate a muscle-specific MUAP template from the profile's
    morphological parameters.
 
    The triphasic model:
      Phase 1 (initial positive) - generated by approaching action potential
      Phase 2 (main negative)    - action potential passing under electrode
      Phase 3 (late positive)    - action potential receding + afterwave
 
    Each phase is a Gaussian whose center, width, and amplitude come
    from the muscle profile. This gives physiologically distinct
    waveforms per muscle rather than one-size-fits-all.
 
    NOTE: the Gaussian triphasic decomposition is a standard simulation
    technique (Stashuk 2001, Nandedkar et al. 1988). Our novel aspect
    is parameterizing it per muscle using the Buchthal duration as the
    scaling anchor.
    """
    duration_ms = profile.muap_duration_ms
    L = int(max(5, round((duration_ms / 1000.0) * fs)))
    tt = np.linspace(0, duration_ms / 1000.0, L)
    t_mean = tt.mean()
 
    # phase positions are relative (0-1) scaled to the MUAP duration
    centers = profile.phase_centers
    widths = profile.phase_widths
    amps = profile.phase_amplitudes
 
    t_p1 = centers[0] * t_mean
    t_p2 = centers[1] * t_mean
    t_p3 = centers[2] * t_mean
 
    # Triphasic MUAP: initial positive, main negative, small positive afterwave
    # This triphasic structure generalizes to all muscles with different parameters
    tpl = (
        amps[0] * np.exp(-((tt - t_p1) ** 2) / (2 * widths[0] ** 2))
        - amps[1] * np.exp(-((tt - t_p2) ** 2) / (2 * widths[1] ** 2))
        + amps[2] * np.exp(-((tt - t_p3) ** 2) / (2 * widths[2] ** 2))
    )
 
    tpl = tpl / (np.max(np.abs(tpl)) + 1e-12)
    return tpl
 
 
# ---------------------------------------------------------------------------
# Recruitment model
#
# Size principle: smaller motor units are recruited first and fire at
# higher rates (Henneman 1957). As contraction level increases, larger
# (and slower-firing) units join in.
#
# The "onion skin" property (De Luca & Erim 1994, De Luca & Hostage 2010)
# establishes that earlier-recruited motor units maintain higher firing
# rates than later-recruited ones at any given force level.
#
# For "synchronous" recruitment (some facial/small muscles), motor units
# tend to fire more in phase, producing a less interference-pattern-like
# and more discrete-looking EMG (Van Boxtel & Schomaker 1983).
#
# The "rule of fives" (Medscape EMG recruitment overview): motor units
# begin firing at ~5 Hz, second MU recruited when first reaches ~10 Hz.
# Rubin & Lamb 2023: fastest firing rate upper limit 12-15 Hz at
# low-moderate contraction across six common muscles.
# ---------------------------------------------------------------------------
 
def _recruit_firing_rate(
    target_amplitude,
    profile: MuscleProfile,
    contraction_level=1.0,
):
    """
    Determine firing rate and number of active motor units based on
    contraction level and the muscle's recruitment characteristics.
 
    Returns (firing_rate_hz, n_active_fraction) where n_active_fraction
    is 0-1 representing what fraction of the motor pool is active.
    """
    fr_min, fr_max = profile.firing_rate_range
    level = np.clip(target_amplitude * contraction_level, 0.0, 1.5)
 
    if profile.recruitment_style == "synchronous":
        # synchronous: fewer units fire but more in unison
        firing_rate = fr_min + (fr_max - fr_min) * min(1.0, level * 1.2)
        n_active = 0.4 + 0.4 * min(1.0, level)
    else:
        # graded (size principle): rate coding at low levels,
        # recruitment of new units at higher levels
        firing_rate = fr_min + (fr_max - fr_min) * min(1.0, level * 0.8)
        n_active = 0.2 + 0.7 * min(1.0, level)
 
    return firing_rate, n_active
 
 
# ---------------------------------------------------------------------------
# Core EMG generator
# ---------------------------------------------------------------------------
 
def generate_emg_signal(
    duration=60,
    fs=1000,
    muscle="diaphragm",
    contraction_rate=15.0,
    contraction_pattern="phasic",
    amplitude_variability=0.1,
    noise_level=0.04,
    contraction_level=1.0,
):
    """
    Generate a realistic surface EMG signal for any muscle.
 
    MUAP-based spikes + band-limited noise bursts under physiological
    envelope, with muscle-specific morphology, firing rates, spectral
    content, and recruitment behavior.
 
    Parameters
    ----------
    duration : float
        Total signal length in seconds.
    fs : int
        Sampling frequency in Hz.
    muscle : str or MuscleProfile
        Either a key from MUSCLE_PROFILES (e.g., "biceps_brachii") or
        a custom MuscleProfile.
    contraction_rate : float
        Rate of phasic contractions per minute (for phasic pattern),
        or ignored for tonic pattern. For respiratory muscles this is
        breaths per minute.
    contraction_pattern : str
        "phasic" for rhythmic bursts (breathing, gait, etc.) or
        "tonic" for sustained contraction (postural, isometric hold).
    amplitude_variability : float
        Fractional variability around target amplitude per burst.
    noise_level : float
        Additive Gaussian noise level within bursts.
    contraction_level : float
        Overall contraction intensity (0-1.5). Affects firing rate and
        motor unit recruitment via the size principle model.
 
    Returns
    -------
    t : ndarray
        Time vector.
    emg : ndarray
        EMG signal.
    """
    # -- Resolve muscle profile --
    if isinstance(muscle, MuscleProfile):
        profile = muscle
    elif isinstance(muscle, str) and muscle in MUSCLE_PROFILES:
        profile = MUSCLE_PROFILES[muscle]
    else:
        available = ", ".join(MUSCLE_PROFILES.keys())
        raise ValueError(
            f"Unknown muscle '{muscle}'. Available: {available}. "
            f"Or pass a custom MuscleProfile instance."
        )
 
    # ------ Time set up ------
    t = np.linspace(0, duration, int(duration * fs))
    emg = np.zeros_like(t)
 
    # ------ Contraction timing ------
    # phasic: rhythmic bursts (like breathing, walking)
    # tonic: sustained contraction tiled across entire duration
    if contraction_pattern == "phasic":
        burst_interval = 60.0 / max(1e-3, contraction_rate)
        burst_times = np.arange(0.5 * burst_interval, duration, burst_interval)
    elif contraction_pattern == "tonic":
        # for tonic, we tile overlapping bursts to create continuous activity
        burst_dur_mid = np.mean(profile.burst_duration_range)
        burst_times = np.arange(0.0, duration, burst_dur_mid * 0.7)
    else:
        raise ValueError(
            f"contraction_pattern must be 'phasic' or 'tonic', "
            f"got '{contraction_pattern}'"
        )
 
    # will be used in for loop below - muscle-specific realistic MUAP
    muap = _muap_template(fs, profile)
 
    # basic filtering cutoff frequencies -> muscle-specific EMG spectrum
    lowcut = profile.spectral_band[0]
    highcut = min(profile.spectral_band[1], fs / 2.0 - 5.0)
    use_band = lowcut < highcut
 
    # cycling contractions
    for bt in burst_times:
        # strong EMG burst w/ variability in amplitude height
        amp = contraction_level + np.random.uniform(
            -amplitude_variability, amplitude_variability
        )
        amp = max(0.0, amp)
 
        # recruitment model determines firing rate and active motor unit fraction
        firing_rate_hz, active_fraction = _recruit_firing_rate(
            amp, profile, contraction_level
        )
 
        # sample burst duration from the muscle's characteristic range
        burst_duration = np.random.uniform(*profile.burst_duration_range)
 
        # how many samples fit in this burst
        N = int(round(burst_duration * fs))
        if N < 4:
            continue
 
        if amp <= 0.01:
            continue
 
        # apply per-burst irregularity to final amplitude
        final_amp = amp * (1 + np.random.uniform(-0.05, 0.05))
 
        wn = np.random.randn(N)
        if use_band:
            sos = signal.butter(
                4,
                [lowcut / (fs / 2.0), highcut / (fs / 2.0)],
                btype="band",
                output="sos",
            )
            burst_noise = signal.sosfiltfilt(sos, wn)
        else:
            burst_noise = wn
 
        if np.std(burst_noise) > 0:
            burst_noise = burst_noise / np.std(burst_noise)
 
        # Many MUAPs overlap -> "spiky" realistic EMG look.
        # spike train of MUAPs - firing rates scaled by recruitment model
        if firing_rate_hz > 0:
            # active_fraction scales the number of concurrent motor units
            expected_spikes = max(
                1, int(round(firing_rate_hz * burst_duration * active_fraction))
            )
            spike_times_rel = np.sort(
                np.random.rand(expected_spikes)
                * max(0.0, burst_duration - 1.0 / fs)
            )
 
            # synchronous recruitment: cluster spike times closer together
            if profile.recruitment_style == "synchronous":
                center = np.mean(spike_times_rel)
                spike_times_rel = center + (spike_times_rel - center) * 0.5
 
            spike_train = np.zeros(N)
            for st in spike_times_rel:
                idx = int(round(st * fs))
                L = len(muap)
                end = min(N, idx + L)
                spike_train[idx:end] += muap[: end - idx]
        else:
            spike_train = np.zeros(N)
 
        # Contraction envelope shape depends on pattern
        envelope_time = np.linspace(0, 1, N)
        if contraction_pattern == "phasic":
            # Respiratory envelope - asymmetric like real inspiration
            # (quick rise, slower fall)
            respiratory_envelope = np.exp(-3 * envelope_time) * (
                1 - np.exp(-8 * envelope_time)
            )
            env_max = np.max(respiratory_envelope)
            burst_envelope = (
                respiratory_envelope / env_max
                if env_max > 0
                else respiratory_envelope
            )
        else:
            # tonic: trapezoidal with soft edges for sustained contraction
            ramp_frac = 0.1
            burst_envelope = np.ones(N)
            ramp_len = int(N * ramp_frac)
            if ramp_len > 0:
                burst_envelope[:ramp_len] = np.linspace(0, 1, ramp_len)
                burst_envelope[-ramp_len:] = np.linspace(1, 0, ramp_len)
 
        carrier = 0.6 * burst_noise + 1.0 * spike_train
        if np.std(carrier) > 0:
            carrier = carrier / np.std(carrier)
 
        burst = final_amp * burst_envelope * carrier
        burst += np.random.normal(0, noise_level, N)
 
        start_idx = int(round(bt * fs))
        end_idx = min(start_idx + N, len(t))
        if start_idx < len(t):
            emg[start_idx:end_idx] += burst[: end_idx - start_idx]
 
    # adding baseline noise and drift
    emg += profile.baseline_noise * np.random.randn(len(t))
 
    # gaussian features - subtle cardiac artifact common in surface EMG
    # amplitude depends on muscle proximity to heart
    heart_rate_hz = np.random.uniform(1.0, 1.33)  # 60-80 bpm
    emg += profile.cardiac_artifact * np.sin(2 * np.pi * heart_rate_hz * t)
 
    # low frequency drift
    emg += profile.drift_amplitude * np.sin(
        2 * np.pi * np.random.uniform(0.03, 0.08) * t
    )
 
    return t, emg
 
 
# ---------------------------------------------------------------------------
# Optional: parameter sampling for researchers who want randomized but
# realistic configurations. Call this to get a dict of baseline
# generation parameters, then unpack into generate_emg_signal().
# ---------------------------------------------------------------------------
 
def sample_emg_params(muscle="diaphragm", seed=None):
    """
    Sample randomized but physiologically plausible generation parameters
    for a given muscle. Useful when there is a need for many synthetic samples with
    natural variation.
 
    Returns a dict that can unpack directly into generate_emg_signal().
    """
    if seed is not None:
        np.random.seed(seed)
 
    if isinstance(muscle, str) and muscle in MUSCLE_PROFILES:
        profile = MUSCLE_PROFILES[muscle]
    elif isinstance(muscle, MuscleProfile):
        profile = muscle
    else:
        profile = MUSCLE_PROFILES["diaphragm"]
 
    fr_min, fr_max = profile.firing_rate_range
 
    return {
        "muscle": profile,
        "contraction_rate": np.random.uniform(
            max(1.0, fr_min * 0.3), fr_max * 0.5
        ),
        "amplitude_variability": np.random.uniform(0.05, 0.2),
        "noise_level": np.random.uniform(0.02, 0.08),
        "contraction_level": np.random.uniform(0.3, 1.2),
    }
